//! GENERATED by scripts/gen-cost-tables.py - do not edit by hand; re-run the script (card #298).
//!
//! The embedded, dated data the cost wizard (`lss-collector cost-setup`) prices a ZIP code with,
//! with no network. Every number below comes from one of these, fetched when this was generated:
//!
//! RATES - U.S. Energy Information Administration (EIA), Electric Power Monthly, Table 5.6.A
//!   "Average Price of Electricity to Ultimate Customers by End-Use Sector, by State",
//!   RESIDENTIAL sector, 2026-06 (preliminary), cents per kWh; page released August 26, 2026.
//!   https://www.eia.gov/electricity/monthly/epm_table_grapher.php?t=epmt_5_6_a
//!   sha256 of the page as fetched: 24d91de23c75b5bdd6df9b59da61f25ad5ebaddb5856d95bb2a200ef375e252b
//! ZIP PREFIX -> STATE - U.S. Census Bureau, 2020 ZCTA-to-county relationship file: each ZCTA's
//!   state is the county holding most of its land, and each 3-digit prefix takes the MAJORITY
//!   state of its ZCTAs. Prefixes whose ZCTAs straddle a state line (the majority wins; the few
//!   border ZIPs of the minority state get their neighbour's average), ZCTA counts per state:
//!   035:NH19/ME1 063:CT35/NY1 422:KY29/TN1 562:MN73/SD1 576:SD31/ND1 723:AR57/TN1 739:OK15/TX1 798:TX20/NM1
//!   820:WY21/CO1 829:WY18/UT1 831:WY17/ID1 834:ID41/WY1 865:AZ19/NM1 873:NM22/AZ1 894:NV45/OR1 967:HI77/AS1
//!   969:GU7/MP3 976:OR21/CA1
//!   https://www2.census.gov/geo/docs/maps-data/data/rel2020/zcta520/tab20_zcta520_county20_natl.txt
//!   sha256: 3ed41278d637dc249e0323306f68be8a6c234e3090f4de88ef328dee71aeaaaf
//! PO-BOX / BUSINESS / MILITARY PREFIXES the Census file cannot see (no land area) - GeoNames US
//!   postal codes (CC BY 4.0, https://www.geonames.org/), majority state per prefix; AA/AE/AP =
//!   the USPS military "states" (APO/FPO/DPO) - a military prefix in the USPS ranges (340 AA,
//!   090-098 AE, 962-966 AP) that neither source lists is filled from those ranges:
//!   005=NY 055=MA 090=AE 091=AE 092=AE 093=AE 094=AE 095=AE
//!   096=AE 097=AE 098=AE 192=PA 311=GA 332=FL 340=AA 375=TN
//!   399=GA 459=OH 509=IA 555=MN 569=DC 649=MO 733=TX 842=UT
//!   876=NM 885=TX 889=NV 901=CA 938=CA 942=CA 962=AP 963=AP
//!   964=AP 965=AP 966=AP
//!   https://download.geonames.org/export/zip/US.zip
//!   sha256 of US.txt: a2e9aa82edb6037deb1c5524c74cd7c948d337fb43c06a216d470989e901647f
//!
//! An empty string = no ZIP code uses that prefix in either source (e.g. 000-004): the wizard
//! says so and asks again rather than guessing a state.

/// The EIA month the rates describe ("YYYY-MM") - shown next to every rate the wizard writes.
pub const EIA_MONTH: &str = "2026-06";
/// When EIA published the page the rates were read from.
pub const EIA_RELEASED: &str = "August 26, 2026";
pub const EIA_SOURCE: &str = "EIA Electric Power Monthly, Table 5.6.A (average residential price by state)";
pub const EIA_URL: &str = "https://www.eia.gov/electricity/monthly/epm_table_grapher.php?t=epmt_5_6_a";

/// (state code, cents per kWh) - 50 states, DC, and "US" (the U.S. total row), residential.
pub const RESIDENTIAL_CENTS_PER_KWH: [(&str, f64); 52] = [
    ("AK", 28.21),
    ("AL", 16.40),
    ("AR", 14.12),
    ("AZ", 15.18),
    ("CA", 34.74),
    ("CO", 17.13),
    ("CT", 24.32),
    ("DC", 24.39),
    ("DE", 19.29),
    ("FL", 15.10),
    ("GA", 16.36),
    ("HI", 52.72),
    ("IA", 15.93),
    ("ID", 14.37),
    ("IL", 19.89),
    ("IN", 17.51),
    ("KS", 15.71),
    ("KY", 14.26),
    ("LA", 13.49),
    ("MA", 29.61),
    ("MD", 21.84),
    ("ME", 29.59),
    ("MI", 22.99),
    ("MN", 17.52),
    ("MO", 16.22),
    ("MS", 14.88),
    ("MT", 15.14),
    ("NC", 14.74),
    ("ND", 14.12),
    ("NE", 13.25),
    ("NH", 27.01),
    ("NJ", 24.95),
    ("NM", 15.06),
    ("NV", 13.11),
    ("NY", 29.49),
    ("OH", 19.19),
    ("OK", 14.33),
    ("OR", 16.32),
    ("PA", 21.73),
    ("RI", 29.23),
    ("SC", 15.55),
    ("SD", 15.36),
    ("TN", 14.07),
    ("TX", 15.94),
    ("US", 18.34),
    ("UT", 13.37),
    ("VA", 17.22),
    ("VT", 24.44),
    ("WA", 14.91),
    ("WI", 19.56),
    ("WV", 15.45),
    ("WY", 15.24),
];

/// Index = the ZIP code's first three digits as a number (so "005" is index 5 - leading zeros
/// are the index, never lost). Value = USPS state/territory code, or "" for an unused prefix.
pub const ZIP3_STATE: [&str; 1000] = [
    "", "", "", "", "", "NY", "PR", "PR", "VI", "PR", "MA", "MA", "MA", "MA", "MA", "MA", "MA", "MA", "MA", "MA",
    "MA", "MA", "MA", "MA", "MA", "MA", "MA", "MA", "RI", "RI", "NH", "NH", "NH", "NH", "NH", "NH", "NH", "NH", "NH", "ME",
    "ME", "ME", "ME", "ME", "ME", "ME", "ME", "ME", "ME", "ME", "VT", "VT", "VT", "VT", "VT", "MA", "VT", "VT", "VT", "VT",
    "CT", "CT", "CT", "CT", "CT", "CT", "CT", "CT", "CT", "CT", "NJ", "NJ", "NJ", "NJ", "NJ", "NJ", "NJ", "NJ", "NJ", "NJ",
    "NJ", "NJ", "NJ", "NJ", "NJ", "NJ", "NJ", "NJ", "NJ", "NJ", "AE", "AE", "AE", "AE", "AE", "AE", "AE", "AE", "AE", "",
    "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY",
    "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY",
    "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "NY", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA",
    "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA",
    "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "PA", "DE", "DE", "DE",
    "DC", "VA", "DC", "DC", "DC", "DC", "MD", "MD", "MD", "MD", "MD", "MD", "MD", "", "MD", "MD", "MD", "MD", "MD", "MD",
    "VA", "VA", "VA", "VA", "VA", "VA", "VA", "VA", "VA", "VA", "VA", "VA", "VA", "VA", "VA", "VA", "VA", "VA", "VA", "VA",
    "VA", "VA", "VA", "VA", "VA", "VA", "VA", "WV", "WV", "WV", "WV", "WV", "WV", "WV", "WV", "WV", "WV", "WV", "WV", "WV",
    "WV", "WV", "WV", "WV", "WV", "WV", "WV", "WV", "WV", "", "NC", "NC", "NC", "NC", "NC", "NC", "NC", "NC", "NC", "NC",
    "NC", "NC", "NC", "NC", "NC", "NC", "NC", "NC", "NC", "NC", "SC", "SC", "SC", "SC", "SC", "SC", "SC", "SC", "SC", "SC",
    "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA", "GA",
    "FL", "FL", "FL", "FL", "FL", "FL", "FL", "FL", "FL", "FL", "FL", "FL", "FL", "FL", "FL", "FL", "FL", "FL", "FL", "FL",
    "AA", "FL", "FL", "", "FL", "", "FL", "FL", "", "FL", "AL", "AL", "AL", "", "AL", "AL", "AL", "AL", "AL", "AL",
    "AL", "AL", "AL", "AL", "AL", "AL", "AL", "AL", "AL", "AL", "TN", "TN", "TN", "TN", "TN", "TN", "TN", "TN", "TN", "TN",
    "TN", "TN", "TN", "TN", "TN", "TN", "MS", "MS", "MS", "MS", "MS", "MS", "MS", "MS", "MS", "MS", "MS", "MS", "GA", "GA",
    "KY", "KY", "KY", "KY", "KY", "KY", "KY", "KY", "KY", "KY", "KY", "KY", "KY", "KY", "KY", "KY", "KY", "KY", "KY", "",
    "KY", "KY", "KY", "KY", "KY", "KY", "KY", "KY", "", "", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH",
    "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH", "OH",
    "IN", "IN", "IN", "IN", "IN", "IN", "IN", "IN", "IN", "IN", "IN", "IN", "IN", "IN", "IN", "IN", "IN", "IN", "IN", "IN",
    "MI", "MI", "MI", "MI", "MI", "MI", "MI", "MI", "MI", "MI", "MI", "MI", "MI", "MI", "MI", "MI", "MI", "MI", "MI", "MI",
    "IA", "IA", "IA", "IA", "IA", "IA", "IA", "IA", "IA", "IA", "IA", "IA", "IA", "IA", "IA", "IA", "IA", "", "", "",
    "IA", "IA", "IA", "IA", "IA", "IA", "IA", "IA", "IA", "", "WI", "WI", "WI", "", "WI", "WI", "", "WI", "WI", "WI",
    "WI", "WI", "WI", "WI", "WI", "WI", "WI", "WI", "WI", "WI", "MN", "MN", "", "MN", "MN", "MN", "MN", "MN", "MN", "MN",
    "MN", "MN", "MN", "MN", "MN", "MN", "MN", "MN", "", "DC", "SD", "SD", "SD", "SD", "SD", "SD", "SD", "SD", "", "",
    "ND", "ND", "ND", "ND", "ND", "ND", "ND", "ND", "ND", "", "MT", "MT", "MT", "MT", "MT", "MT", "MT", "MT", "MT", "MT",
    "IL", "IL", "IL", "IL", "IL", "IL", "IL", "IL", "IL", "IL", "IL", "IL", "IL", "IL", "IL", "IL", "IL", "IL", "IL", "IL",
    "IL", "", "IL", "IL", "IL", "IL", "IL", "IL", "IL", "IL", "MO", "MO", "", "MO", "MO", "MO", "MO", "MO", "MO", "MO",
    "MO", "MO", "", "", "MO", "MO", "MO", "MO", "MO", "MO", "MO", "MO", "MO", "MO", "MO", "MO", "MO", "MO", "MO", "",
    "KS", "KS", "KS", "", "KS", "KS", "KS", "KS", "KS", "KS", "KS", "KS", "KS", "KS", "KS", "KS", "KS", "KS", "KS", "KS",
    "NE", "NE", "", "NE", "NE", "NE", "NE", "NE", "NE", "NE", "NE", "NE", "NE", "NE", "", "", "", "", "", "",
    "LA", "LA", "", "LA", "LA", "LA", "LA", "LA", "LA", "", "LA", "LA", "LA", "LA", "LA", "", "AR", "AR", "AR", "AR",
    "AR", "AR", "AR", "AR", "AR", "AR", "AR", "AR", "AR", "AR", "OK", "OK", "", "TX", "OK", "OK", "OK", "OK", "OK", "OK",
    "OK", "OK", "", "OK", "OK", "OK", "OK", "OK", "OK", "OK", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX",
    "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX",
    "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX", "TX",
    "CO", "CO", "CO", "CO", "CO", "CO", "CO", "CO", "CO", "CO", "CO", "CO", "CO", "CO", "CO", "CO", "CO", "", "", "",
    "WY", "WY", "WY", "WY", "WY", "WY", "WY", "WY", "WY", "WY", "WY", "WY", "ID", "ID", "ID", "ID", "ID", "ID", "ID", "",
    "UT", "UT", "UT", "UT", "UT", "UT", "UT", "UT", "", "", "AZ", "AZ", "AZ", "AZ", "", "AZ", "AZ", "AZ", "", "AZ",
    "AZ", "", "", "AZ", "AZ", "AZ", "", "", "", "", "NM", "NM", "", "NM", "NM", "NM", "NM", "NM", "NM", "NM",
    "NM", "NM", "NM", "NM", "NM", "TX", "", "", "", "NV", "NV", "NV", "", "NV", "NV", "NV", "", "NV", "NV", "",
    "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA",
    "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA",
    "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA", "CA",
    "CA", "CA", "AP", "AP", "AP", "AP", "AP", "HI", "HI", "GU", "OR", "OR", "OR", "OR", "OR", "OR", "OR", "OR", "OR", "OR",
    "WA", "WA", "WA", "WA", "WA", "WA", "WA", "", "WA", "WA", "WA", "WA", "WA", "WA", "WA", "AK", "AK", "AK", "AK", "AK",
];
